hydra/urls.py
from hydra import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hydrasite.views.home', name='home'),
    # url(r'^hydrasite/', include('hydrasite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'hydra.views.index'),
	  url(r'^static/(?P<path>.*)$', 'django.views.static.serve',  
	         {'document_root': settings.STATIC_ROOT}),
    
)

hydra/models.py
from django.db import models
from django.forms import ModelForm
from django.core.exceptions import ValidationError

def validate_only_one_instance(obj):
    model = obj.__class__
    if (model.objects.count() > 0 and
            obj.id != model.objects.get().id):
        raise ValidationError("Can only create 1 %s instance" % model.__name__)



class AboutCopy(models.Model):
	about_title = models.CharField(max_length=250,default="About")
	about_text_left = models.TextField(default="what we do")
	about_text_right = models.TextField(default="more about us")
	def clean(self):
	        validate_only_one_instance(self)
	
	
class NewsletterSignup(models.Model):
	firstname = models.CharField(max_length=250)
	email = models.EmailField(max_length=75)
	
class NewsletterForm(ModelForm):
	class Meta:
		model = NewsletterSignup
		
		def __init__(self, *args, **kwargs):
		        super(NewsletterForm, self).__init__(*args, **kwargs)
		        self.fields['myfield'].widget.attrs.update({'size' : '80'})

hydra/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, Context, loader
from hydra.models import AboutCopy, NewsletterSignup, NewsletterForm
from django.shortcuts import render_to_response
from django.core.context_processors import csrf
from django.utils import simplejson




def index(request):
	c = {}
	c.update(csrf(request))
	thanks = 1
	aboutcopy = AboutCopy.objects.get(pk=1)
	abouthead = aboutcopy.about_title
	aboutleft = aboutcopy.about_text_left
	aboutright = aboutcopy.about_text_right
	post = request.POST.copy()
	if request.method == 'POST': 
		form = NewsletterForm(post) 
		if post: 
			firstname = post['name']
			email = post['email']
			signup = NewsletterSignup()
			signup.email = email
			signup.firstname = firstname
			signup.save()
			status = simplejson.dumps({'status': "success"})
			return HttpResponse(status, mimetype="application/json")

	else:
		form = NewsletterForm() # An unbound form

		return render_to_response('hydra/index.html', {
			'form': form, 'abouthead': abouthead, 'aboutleft': aboutleft, 'aboutright': aboutright,
			},context_instance=RequestContext(request))

			
			
			
			

hydra/templates/hydra/index.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">

	<!-- Use the .htaccess and remove these lines to avoid edge case issues.
	More info: h5bp.com/i/378 -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>HYDRA</title>
	<meta name="description" content="">

	<!-- Mobile viewport optimized: h5bp.com/viewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- Boilerplate stylesheet -->
	<link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" media="screen">

	<!-- 1140px Grid styles for IE -->
	<!--[if lte IE 9]><link rel="stylesheet" href="{{ STATIC_URL }}css/ie.css" type="text/css" media="screen" /><![endif]-->

	<!-- The 1140px Grid - http://cssgrid.net/ -->
	<link rel="stylesheet" href="{{ STATIC_URL }}css/1140.css" type="text/css" media="screen" />
	<!--css3-mediaqueries-js - http://code.google.com/p/css3-mediaqueries-js/ - Enables media queries in some unsupported browsers-->
	<script type="text/javascript" src="{{ STATIC_URL }}js/css3-mediaqueries.js"></script>

	<!-- All JavaScript at the bottom, except this Modernizr build.
	Modernizr enables HTML5 elements & feature detects for optimal performance.
	Create your own custom Modernizr build: www.modernizr.com/download/ -->
	<script src="{{ STATIC_URL }}js/libs/modernizr-2.5.3.min.js"></script>
	
	<!-- TypeKit script -->
	<script type="text/javascript" src="http://use.typekit.com/kcq7fyc.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	
</head>
<body>
	<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
	chromium.org/developers/how-tos/chrome-frame-getting-started -->
	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
	<header id="header">
		<div class="container">
			<div class="row">
				<div class="headercol" id="logo">
					<img src="{{ STATIC_URL }}img/logo.png">
				</div>
				<div class="headercol"><div class="verticalline"><a class="aboutactivator" id="aboutactivator"><p class="topnav"><strong>ABOUT US/</strong><br>WHAT WE DO</p></a></div></div>
				<div class="headercol"><div class="verticalline"><a class="newsletteractivator" id="newsletteractivator"><p class="topnav"><strong>NEWSLETTER/</strong><br>SIGN UP</p></a></div></div>
			</div>
		</div>
	</header>




	<div role="main">

		
		<!-- about overlay -->
		<div class="aboutoverlay" id="aboutoverlay" style="display:none;">
			<div class="container">
				<div class="row">
					<div class="elevencol">
					</div>
					<div class="boxcol">
						<a class="boxclose" id="boxclose" style="align:right;"></a>
					</div>
				</div>
			</div>
		</div>
		<div class="aboutbox" id="aboutbox">
			<h1>{{ abouthead }}</h1>
			<!-- onecol about -->			
			<div class="aboutsinglecol">
				{{ aboutleft }}  {{ aboutright }}
			</div>
			<!-- twocol about -->
			<div class="container">
				<div class="row">
					<div class="abouttext">
					<div class="fourcol" style="margin-right:10px;">
						{{ aboutleft }}
					</div>
					<div class="fourcol">
						{{ aboutright }}
					</div>
					</div>
				</div>
			</div>
		</div>


		<!-- newsletter overlay -->
		<div class="newsletteroverlay" id="newsletteroverlay" style="display:none;">
		</div>
		<div class="newsletterbox" id="newsletterbox">
			<div class="container" id="newsletterwide">
				<div class="row">
				<div class="fivecol" style="text-align:left;">
				<p class="topnav"><strong>NEWSLETTER/</strong> SIGN UP FOR UPDATES</p>
				</div>
				</div>
				<div class="row" id="signrow">
					<div class="signcol" style="margin-top:10px;margin-right:0px;">
						<form name="myForm" action="" onsubmit="return validateEmail()" >
						<input class="signupinput" type="text" name="firstname" id="id_firstname" value="YOUR NAME" />
					</div>
					<div class="signcol" style="margin-top:10px;">
							<input class="signupinput" type="text" name="email" id="id_email" value="YOUR EMAIL" />
					</div>
					<div class="subcol">
							<button class="signup" type="submit" id="signup">SIGN UP</button>
					</div>
					<div class="boxcol" id="newboxcol">
						<a class="newsletterboxclose" id="newsletterboxclose"></a>
					</div>
				</div>
			</div>
		</div>	
		

		<!-- thanks overlay -->
			<div class="thanksoverlay" id="thanksoverlay" style="display:none;">
			</div>
			<div class="thanksbox" id="thanksbox">
				<div class="container">
					<div class="row" id="thanksrow">
						<div class="thankscol">
							<p class="topnav" style="font-size:.5em;">Thanks for signing up!</p>
						</div>
						<div class="thankscol">
							<a class="thanksclose" id="thanksclose"></a>
						</div>
					</div>
				</div>
			</div>
	
 		<!-- main singlecol -->
			<div class="singlecol" id="logo">
				<img src="{{ STATIC_URL }}img/logo.png">
			</div>
			<div id="mobilemain">
			<div class="singlecol"><div class="verticalline"><a class="aboutactivator" id="aaboutactivator"><p class="topnav"><strong>ABOUT US/</strong><br>WHAT WE DO</p></a></div></div>
			<div class="singlecol"><div class="verticalline"><a class="newsletteractivator" id="nnewsletteractivator"><p class="topnav"><strong>NEWSLETTER/</strong><br>SIGN UP</p></a></div></div>

			<div class="singlecol"><div class="verticalline"><p class="topnav"><strong>EMAIL</strong><br><a href="mailto:info@hydra.com">INFO@HYDRA.COM</a></p></div></div>
			<div class="singlecol"><div class="verticalline" style="border-bottom:none;"><p class="topnav"><strong>PHONE</strong><br>800-123-4567</p></div></div>
			</div>

		<!-- html5 background video 
		<video id="bg_video" src="{{ STATIC_URL }}img/bg.webm" autoplay="true" loop="true"></video>
		<video id="bg_video_safari" style="display:none;" src="{{ STATIC_URL }}img/bg.mp4" autoplay="true" loop="true"></video>
		-->
		
	</div>

	<footer id="footer">
		<div class="container">
			<div class="row">
				<div class="ninecol">
					<p class="darkgrey" id="footertext" style="margin-bottom:2%;"><strong style="color:#ffffff;">HYDRA.</strong> | &copy; 2012 Hydra. All Rights Reserved.</p>
				</div>
				<div class="onecol" id="footercontact" style="text-align:left;">
					<p class="footerverticalline" id="footertext">EMAIL<br><strong class="lightgrey"><a href="mailto:info@hydra.com">INFO@HYDRA.COM</a></strong>
					</p>
				</div>
				<div class="onecol" id="footerphonecontact">
					<p class="footerverticalline" id="footertext">PHONE<br><strong class="lightgrey">800-123-4567</strong>
					</p>
				</div>
			</div>
		</div>
	</footer>


	<!-- JavaScript at the bottom for fast page loading -->

	<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.7.1.min.js"><\/script>')</script>

	<!-- scripts concatenated and minified via build script -->
	<script src="{{ STATIC_URL }}js/plugins.js"></script>
	<script src="{{ STATIC_URL }}js/script.js"></script>
	<!-- end scripts -->

	<!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
	mathiasbynens.be/notes/async-analytics-snippet -->
	<script>
	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
	
</body>
</html>